[package]
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
name = "opengltesting"
version = "0.1.0"

[dependencies]
cgmath = "0.15.0"
gl = "0.6.3"
glfw = "0.17.0"
image = "0.15.0"
notify = "4.0.1"
